pipeline:
  publish:
    image: maven:3.5-jdk-8
    environment:
      - MAVEN_USERNAME=drone
    secrets:
      - maven_password
    commands:
      - mkdir -p ~/.m2
      - >
        echo '<?xml version="1.0" encoding="UTF-8"?>
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
            <server>
              <id>humio-releases</id>
              <username>$${MAVEN_USERNAME}</username>
              <password>$${MAVEN_PASSWORD}</password>
            </server>
            <server>
              <id>humio-public</id>
              <username>$${MAVEN_USERNAME}</username>
              <password>$${MAVEN_PASSWORD}</password>
            </server>
          </servers>
        </settings>' > ~/.m2/settings.xml
      - mvn -B versions:set versions:commit -DnewVersion=1.0-beta-${DRONE_BUILD_NUMBER}
      - mvn -B deploy
    when:
      branch: master

  prepare-universe:
    image: python:3-stretch
    commands:
      - >
        echo '{
          "assets": {
            "uris": {
              "jre-tar-gz": "https://downloads.mesosphere.com/java/jre-8u162-linux-x64.tar.gz",
              "scheduler-jar": "https://repo.humio.com/repository/maven-public/com/humio/mesos/dcos2humio/scheduler/1.0-beta-$${DRONE_BUILD_NUMBER}/scheduler-1.0-beta-$${DRONE_BUILD_NUMBER}.jar",
              "executor-jar": "https://repo.humio.com/repository/maven-public/com/humio/mesos/dcos2humio/executor/1.0-beta-$${DRONE_BUILD_NUMBER}/executor-1.0-beta-$${DRONE_BUILD_NUMBER}.jar",
              "filebeat-tar-gz": "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.1.1-linux-x86_64.tar.gz",
              "metricbeat-tar-gz": "https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-6.1.1-linux-x86_64.tar.gz"
            }
          },
          "images": {
            "icon-small": "https://raw.githubusercontent.com/humio/graphics/master/48.png",
            "icon-medium": "https://raw.githubusercontent.com/humio/graphics/master/96.png",
            "icon-large": "https://raw.githubusercontent.com/humio/graphics/master/256_icon.png"
          }
        }' > universe/packages/H/humio-agent/1/resources.json
      - >
        echo '{
          "packagingVersion": "3.0",
          "name": "humio-agent",
          "framework": true,
          "description": "Log management for developers. Like tail and grep with aggregations and graphs built-in.\\n\\nMake sure you have created an account with a dataspace at https://humio.com",
          "version": "1.0-beta-$${DRONE_BUILD_NUMBER}",
          "scm": "http://github.com/humio/dcos2humio",
          "maintainer": "martin@mwl.dk",
          "tags": ["log", "humio", "monitoring"],
          "preInstallNotes": "This DC/OS Service is currently in preview. There may be bugs, incomplete features, incorrect documentation, or other discrepancies. Experimental packages should never be used in production!",
          "postInstallNotes": "Humio agent has been installed successfully.",
          "postUninstallNotes": "Humio agent was uninstalled successfully.",
          "licenses": [
            {
              "name": "Apache License Version 2.0",
              "url": "https://raw.githubusercontent.com/apache/spark/master/LICENSE"
            }
          ]
        }' > universe/packages/H/humio-agent/1/package.json
      - mkdir -p universe/target
      - pip3 install jsonschema
      - cd universe
      - ./gen_universe.py --repository packages --out-dir target
    when:
      branch: master

  publish-universe-docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: humio/universe
    dockerfile: universe/Dockerfile
    tags: 1.0-beta-${DRONE_BUILD_NUMBER}
    when:
      branch: master

  deploy:
    image: e20co/drone-marathon
    server: http://marathon.mesos:8080
    marathonfile: universe/marathon.json
    values:
      - drone_build_number
    when:
      branch: master
