spring:
  application:
    name: Humio agent scheduler
humio:
  host: go.humio.com
mesos:
  framework:
    name: humio-agent
  master: leader.mesos:5050
  zookeeper:
    server: leader.mesos:2181
  command: |
    jre1.8.0_121/bin/java -jar executor.jar
  resources:
    distinctSlave: true
    cpus: 1
    mem: 512
  uri:
    - https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-5.5.2-linux-x86_64.tar.gz
    - https://downloads.mesosphere.com/java/jre-8u121-linux-x64.tar.gz
    - http://${libprocess.ip}:8000/executor.jar
