spring:
  application:
    name: Humio agent scheduler
humio:
  host: go.humio.com
mesos:
  master: leader.mesos:5050
  zookeeper:
    server: leader.mesos:2181
  command: |
    filebeat-5.5.2-linux-x86_64/filebeat -e -path.data=/var/humio/data -c filebeat-5.5.2-linux-x86_64/filebeat.yml \
      -E 'filebeat.prospectors=[{paths: ["/var/lib/mesos/slave/slaves/*/frameworks/*/executors/*/runs/latest/stdout","/var/lib/mesos/slave/slaves/*/frameworks/*/executors/*/runs/latest/stderr","/var/log/mesos/*.log","/var/log/dcos/dcos.log"]}]' \
      -E 'output.elasticsearch.hosts=["https://${humio.host}:443/api/v1/dataspaces/${humio.dataspace}/ingest/elasticsearch"]' \
      -E 'output.elasticsearch.username=${humio.ingesttoken}' \
      -E 'output.elasticsearch.compression_level=5' \
      -E 'output.elasticsearch.bulk_max_size=200'
  resources:
    distinctSlave: true
    cpus: 0.1
    mem: 32
  uri:
    - https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-5.5.2-linux-x86_64.tar.gz
