spring:
  application:
    name: "humio-agent"
humio:
  host: go.humio.com
  executor:
    version: "1.0-SNAPSHOT"
    url: http://${host}:8085/executor/target/executor-${humio.executor.version}.jar
  dataDir: "/var/humio/data"
  metrics:
    container: false
mesos:
  framework:
    name: humio-agent
  role: "slave_public"
  master: master.mesos:5050
  zookeeper:
    server: master.mesos:2181
  resources:
    distinctSlave: true
    cpus: 0.1
    mem: 512
  webuiUrl: "http://${host}:${server.port}/home"
  uri:
    - https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.3.2-linux-x86_64.tar.gz
    - https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-6.3.2-linux-x86_64.tar.gz
    - https://downloads.mesosphere.com/java/server-jre-8u162-linux-x64.tar.gz
    - ${humio.executor.url}
