spring:
  application:
    name: "humio-agent"
humio:
  host: go.humio.com
  executor:
    version: "1.0-SNAPSHOT"
    url: http://${libprocess.ip}:8000/executor/target/executor-${executor.version}.jar
    dataDir: "/var/humio/data"
mesos:
  framework:
    name: humio-agent
  master: leader.mesos:5050
  zookeeper:
    server: leader.mesos:2181
  resources:
    distinctSlave: true
    cpus: 1
    mem: 512
  webuiUrl: "http://${host}:${server.port}/home"
  uri:
    - https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-5.6.0-linux-x86_64.tar.gz
    - https://downloads.mesosphere.com/java/jre-8u121-linux-x64.tar.gz
    - ${humio.executor.url}
